services:
  - type: web
    name: cfms-app
    env: node
    plan: starter
    buildCommand: "yarn build"
    startCommand: "yarn start"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cfms-db
          property: connectionString
databases:
  - name: cfms-db
    databaseName: cfms
    plan: starter
